runtime: python311
entrypoint: gunicorn -b :$PORT -w 1 -k uvicorn.workers.UvicornWorker app:app

# Service name
service: default

# Environment variables
env_variables:
  GOOGLE_CLOUD_PROJECT: "YOUR-PROJECT-ID"

# Instance configuration
automatic_scaling:
  max_instances: 10
  min_instances: 0
  
resources:
  cpu: 2
  memory_gb: 2
